<?php



function fts_schemaorg_block_info() {


  $blocks = array();
  $blocks['fts_schemaorg'] = array(
      'info' => t('FTS Schema.org'),
    );
  return $blocks;
}



function fts_schemaorg_block_view($delta = '') {
  // if ($delta == 'fts_schemaorg') {
  // 	$microdata = NULL;
  // 	if(arg(0) == 'node') {
  // 		$node = node_load(arg(1));
  // 		if ($node->type == 'news' || $node->type == 'stii_m') {
  // 			// Статьи/Новости
		// 	$image = 'https://advokat-perewerzew.com.ua/sites/all/themes/design/img/advokat.png';
  // 			if (isset($node->field_image[LANGUAGE_NONE][0]['fid'])) {
  // 				$image = image_style_url('200x200', $node->field_image[LANGUAGE_NONE][0]['uri']);
  // 			}

	 //  		$microdata = '<div itemscope itemtype="http://schema.org/Article" class="display_none">
		// 	    <link itemprop="mainEntityOfPage" itemscope href="'.$_SERVER['HTTP_HOST'].$_SERVER['REQUEST_URI'].'" />
		// 	    <span itemprop="headline">'.$node->title.'</span>
		// 	    <div itemprop="description">'.token_replace('[node:metatag:description]', array('node' => $node)).'</div>
		// 	    <span itemprop="datePublished">'.token_replace('[node:metatag:article:published_time]', array('node' => $node)).'</span>
		// 	    <span itemprop="dateModified">'.token_replace('[node:metatag:article:modified_time]', array('node' => $node)).'</span>
		// 	    <span itemprop="image" itemscope itemtype="https://schema.org/ImageObject">
		// 			<img itemprop="image url" src="'.$image.'"/>
		// 			<meta itemprop="width" content="150">
		// 			<meta itemprop="height" content="150">
		// 		</span>
		// 	    <div itemprop="publisher" itemscope itemtype="https://schema.org/Organization">
		// 	        <div itemprop="logo" itemscope itemtype="https://schema.org/ImageObject">
		// 	            <img itemprop="image url" src="https://advokat-perewerzew.com.ua/sites/all/themes/design/img/advokat.png"/>
		// 	            <meta itemprop="width" content="200">
		// 	            <meta itemprop="height" content="200">
		// 	        </div>
		// 	        <meta itemprop="telephone" content="(093) 40 39 250">
		// 	        <meta itemprop="telephone" content="(096) 69 94 888">
		// 	        <meta itemprop="telephone" content="(050) 13 54 578">
		// 	        <meta itemprop="telephone" content="(046) 29 30 261">
		// 	        <meta itemprop="address" content="Украина, Чернигов, ул. Коцюбинского 49а, офис 101">
		// 	        <meta itemprop="name" content="Адвокат Переверзев Александр Александрович">
		// 	    </div>
		// 	    <span itemprop="author">Адвокат Переверзев Александр Александрович</span>
		// 	</div>';

  // 		} else if($node->type == 'uslugi') {
  // 			// Страница контактов (Контакты)
	 //  		$microdata = '<div itemscope itemtype="http://schema.org/Service" class="display_none">
		// 	    <link itemprop="mainEntityOfPage" itemscope href="'.$_SERVER['HTTP_HOST'].$_SERVER['REQUEST_URI'].'" />
		// 	    <span itemprop="name">'.$node->title.'</span>
		// 	    <div itemprop="description">'.token_replace('[node:metatag:description]', array('node' => $node)).'</div>
		// 	    <div itemprop="serviceType">Услуги адвоката</div>
		// 	</div>';
  // 		}
  // 	}
  		
  //   $block = array(
  //       'subject' => NULL,
  //       'content' => $microdata,
  //     );
  // }
  // return $block;  
}



